name: Auto Renew and Deploy SSL Certificates

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: '0 0 20 */2 *' # 每两个月的第二十天执行一次

jobs:
  renew-deploy-cert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Tencent Cloud CLI
      run: pip install tccli

    - name: Set up NodeJS
      uses: pnpm/action-setup@v3
      with:
        version: 9
    
    - name: Install dependencies
      run: pnpm install

    - name: Compile typescript
      run: pnpm run build

    - name: Install acme.sh
      env:
        EMAIL: ${{ secrets.EMAIL}}
      run: |
        sudo apt-get update
        sudo apt-get install -y socat
        curl https://get.acme.sh | sh -s email="${EMAIL}"

    - name: Prepare acme.sh credentials
      env:
        DOMAIN: ${{ secrets.DOMAIN }}
      run: |
        mkdir -p ~/.acme.sh
        mkdir -p ~/certs/${DOMAIN}

    - name: Obtain SSL Certificates
      env:
        DOMAIN: ${{ secrets.DOMAIN }}
        Tencent_SecretId: ${{ secrets.TENCENT_SECRET_ID }}
        Tencent_SecretKey: ${{ secrets.TENCENT_SECRET_KEY }}
      run: |
        ~/.acme.sh/acme.sh --issue --dns dns_tencent -d "*.${DOMAIN}" \
        --key-file ~/certs/${DOMAIN}/privkey.pem --fullchain-file ~/certs/${DOMAIN}/fullchain.pem

    - name: Upload certificates to Alibaba Cloud Certificate Manager
      env:
        ALIYUN_ACCESS_KEY_ID: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
        ALIYUN_ACCESS_KEY_SECRET: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
        # 要设置域名的二级域名，例如要设置*.example.com，这里填写的就是example.com, 多个域名用英文逗号隔开
        DOMAIN: ${{ secrets.DOMAIN }}
        # 设置阿里云cdn域名，一般是三级域名，例如cdn.example.com，需要跟上面的DOMAIN对应，否则会设置错误
        ALIYUN_CDN_DOMAIN: ${{ secrets.ALIYUN_CDN_DOMAIN }}
      run: node dist/upload-ssl.js

    - name: Prepare ossutil
      uses: yizhoumo/setup-ossutil@v2
      env:
        ALIYUN_ACCESS_KEY_ID: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
        ALIYUN_ACCESS_KEY_SECRET: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
      with:
        ossutil-version: '1.7.19'
        endpoint: "https://oss-cn-hangzhou.aliyuncs.com"
        access-key-id: ${ALIYUN_ACCESS_KEY_ID}
        access-key-secret: ${ALIYUN_ACCESS_KEY_SECRET}
    
    - name: ossutil update certificate
      env:
        BUCKET: ${{ secrets.BUCKET }}
        DOMAIN: ${{ secrets.DOMAIN }}
      run: |
        ossutil bucket-cname --method put --item certificate "oss://${BUCKET}" "$HOME/certs/${DOMAIN}/oss_cname.xml"
    
    # - name: Set CNAME for OSS bucket
    #   env:
    #     BUCKET: ${{ secrets.BUCKET }}
    #     DOMAIN: ${{ secrets.DOMAIN }}
    #     ALIYUN_CDN_DOMAIN: ${{ secrets.ALIYUN_CDN_DOMAIN }}
    #     TENCENTCLOUD_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
    #     TENCENTCLOUD_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
    #   run: node set-cname.js

    - name: Clean up
      env:
        DOMAIN: ${{ secrets.DOMAIN }}
      run: |
        rm -rf ~/certs/${DOMAIN}
