name: Auto Renew and Deploy SSL Certificates

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: '0 0 20 */2 *' # 每两个月的第二十天执行一次

jobs:
  renew-deploy-cert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up NodeJS
      uses: pnpm/action-setup@v3
      with:
        version: 9
    
    - name: Install dependencies
      run: pnpm install

    - name: Compile typescript
      run: pnpm run build

    - name: Install acme.sh
      env:
        EMAIL: ${{ secrets.EMAIL}}
      run: |
        sudo apt-get update
        sudo apt-get install -y socat
        curl https://get.acme.sh | sh -s email="${EMAIL}"

    - name: Prepare acme.sh credentials
      run: |
        mkdir -p ~/.acme.sh
        IFS=',' read -r -a domain_array <<< "${{ secrets.DOMAINS }}"
        for domain in "${domain_array[@]}"; do
          mkdir -p ~/certs/${domain}
        done

    - name: Obtain SSL Certificates
      env:
        DOMAINS: ${{ secrets.DOMAINS }}
        Tencent_SecretId: ${{ secrets.TENCENT_SECRET_ID }}
        Tencent_SecretKey: ${{ secrets.TENCENT_SECRET_KEY }}
        Ali_Key: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
        Ali_Secret: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
      run: |
        IFS=',' read -r -a domain_array <<< "${DOMAINS}"
        for domain in "${domain_array[@]}"; do
          ~/.acme.sh/acme.sh --issue --dns dns_tencent -d "*.${domain}" \
          --key-file ~/certs/${domain}/privkey.pem --fullchain-file ~/certs/${domain}/fullchain.pem
        done

    - name: Upload certificates to Alibaba Cloud Certificate Manager
      env:
        ALIYUN_ACCESS_KEY_ID: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
        ALIYUN_ACCESS_KEY_SECRET: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
        # 要设置域名的二级域名，例如要设置*.example.com，这里填写的就是example.com, 多个域名用英文逗号隔开
        DOMAINS: ${{ secrets.DOMAINS }}
        # 设置阿里云cdn域名，一般是三级域名，例如cdn.example.com，需要跟上面的DOMAINS对应，否则会设置错误
        ALIYUN_CDN_DOMAINS: ${{ secrets.ALIYUN_CDN_DOMAINS }}
  
      run: node dist/client.js

    - name: Clean up
      env:
        DOMAINS: ${{ secrets.DOMAINS }}
      run: |
        IFS=',' read -r -a domain_array <<< "${DOMAINS}"
        for domain in "${domain_array[@]}"; do
          rm -rf ~/certs/${domain}
        done
